name: Upstream Sync

on:
  schedule:
    - cron: '0 */4 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Sync upstream
        run: |
          set -e

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote add upstream https://github.com/iptv-org/epg.git
          git fetch upstream master

          git checkout master
          git reset --hard upstream/master

          git push origin master --force
